// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// IntegrMultiCpp
List IntegrMultiCpp(NumericMatrix alpha2, NumericVector linvec2, NumericMatrix Phibig2, NumericMatrix tUeach2, NumericMatrix Ueach2, NumericMatrix Tmat2, NumericMatrix Phidoublebig2, NumericMatrix Udoubleeach2, NumericMatrix XW2);
RcppExport SEXP PenCoxFrail_IntegrMultiCpp(SEXP alpha2SEXP, SEXP linvec2SEXP, SEXP Phibig2SEXP, SEXP tUeach2SEXP, SEXP Ueach2SEXP, SEXP Tmat2SEXP, SEXP Phidoublebig2SEXP, SEXP Udoubleeach2SEXP, SEXP XW2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type linvec2(linvec2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Phibig2(Phibig2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tUeach2(tUeach2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ueach2(Ueach2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Tmat2(Tmat2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Phidoublebig2(Phidoublebig2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Udoubleeach2(Udoubleeach2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type XW2(XW2SEXP);
    __result = Rcpp::wrap(IntegrMultiCpp(alpha2, linvec2, Phibig2, tUeach2, Ueach2, Tmat2, Phidoublebig2, Udoubleeach2, XW2));
    return __result;
END_RCPP
}
